language: swift
osx_image: xcode11.1

script:
  - pod install
  - set -o pipefail && xcodebuild -workspace NatDS.xcworkspace -scheme NatDS -destination platform\=iOS\ Simulator,OS\=13.1,name\=iPhone\ 8 build test | xcpretty