language: swift
osx_image: xcode11.3

before_install:
  - brew update
  - brew install git-lfs
  - git lfs install

install:
  - bundle install

before_script:
  - git lfs pull
  - pod install

script:
   - fastlane test