dictionaries:
  - en
excluded_files:
  - ".typo-ci.yml"
  - "NatDS.xcodeproj/project.pbxproj"
  - "SampleApp/NatDS-SampleApp.xcodeproj/project.pbxproj"
  - "Gemfile.lock"
excluded_words:
  - Buildables
  - cocoapods
  - cocoapods-downloader
  - DarkHorizontal
  - DarkVertical
  - downloader
  - enum
  - Horizontal
  - Inits
  - isa
  - Logo
  - Logo-NaturaCosmeticos-DarkHorizontal
  - Logo-NaturaCosmeticos-DarkVertical
  - Logo-NaturaCosmeticos-Horizontal
  - nat
  - natds-themes
  - natDialogController
  - NatOpacities
  - natura
  - NaturaCosmeticos
  - objc
  - Opacities
  - parallelize
  - parallelizeBuildables
  - pbxproj
  - Testables
  - themes
  - xcassets
  - xcshareddata
  - xcscheme
  - xcschemes
